// frontend/src/react/main/HeaderButtons.tsx
import React from "react";
import { NavLink } from "react-router-dom";

import { UserContext } from "../common/context";
import { getData } from "../common/helpers";

export default function HeaderButtons(): JSX.Element {
  const [user, setUser] = React.useContext(UserContext);
  async function logout() {
    await getData("/auth/logout");
    setUser(null);
  }

  if (user) {
    return (
      <ul>
        <li>
          <NavLink to="/" onClick={logout}>
            Log Out
          </NavLink>
        </li>
      </ul>
    );
  }
  return (
    <ul>
      <li>
        <NavLink to="/register">Register</NavLink>
      </li>
      <li>
        <NavLink to="/login">Log In</NavLink>
      </li>
    </ul>
  );
}

// frontend/src/vue/common/HeaderButtons.vue
<template>
  <ul v-if="user.id">
    <li>
      <router-link to="/" @click.native="logout">Log out</router-link>
    </li>
  </ul>
  <ul v-else>
    <li>
      <router-link to="/register">Register</router-link>
    </li>
    <li>
      <router-link to="/login">Log In</router-link>
    </li>
  </ul>
</template>

<script>
import { mapState, mapMutations } from "vuex";
import { getData } from "./helpers";

export default {
  methods: {
    ...mapMutations(["clearUser"]),
    logout() {
      getData("/auth/logout");
      this.clearUser();
    }
  },
  computed: mapState(["user"])
};
</script>
