// frontend/src/vue/blog/Posts.vue
<template>
  <section key="section" class="content">
    <header>
      <h1>Posts</h1>
      <router-link v-if="user.id" to="/create" class="action">
        New
      </router-link>
    </header>
    <article v-for="post in posts" :key="post.id" class="post">
      <header>
        <div>
          <h1>{{ post.title }}</h1>
          <div class="about">by {{ post.username }} on {{ post.created }}</div>
        </div>
        <router-link
          v-if="user && Number(user.id) === Number(post.author_id)"
          :to="postUrl(post.id)"
          class="action"
        >
          Edit
        </router-link>
      </header>
      <p class="body">
        {{ post.body }}
      </p>
    </article>
  </section>
</template>

<script>
import { mapState } from "vuex";
import { getData } from "../common/helpers";

export default {
  data: () => ({
    posts: []
  }),
  computed: mapState(["user"]),
  async mounted() {
    this.posts = await getData("/blog/posts");
  },
  methods: {
    postUrl(postID) {
      return `/post/${postID}`;
    }
  }
};
</script>

// frontend/src/react/blog/Posts.tsx
import React from "react";
import { NavLink } from "react-router-dom";
import { getData } from "../common/helpers";
import { UserContext } from "../common/context";
import useTitle from "../common/useTitle";

export interface Post {
  id: number;
  title: string;
  username: string;
  created: string;
  author_id: string;
  body: string;
}

const usePosts = () => {
  const [posts, setPosts] = React.useState<Post[]>([]);

  React.useEffect(() => {
    const fetch = async () => {
      const data = await getData<Post[]>("/blog/posts");
      setPosts(data);
    };
    fetch();
  }, []);
  return posts;
};

const Posts = () => {
  useTitle("Posts");
  const [user] = React.useContext(UserContext);
  const posts = usePosts();

  const renderPosts = posts.map((post) => (
    <article className="post" key={post.id}>
      <header>
        <div>
          <h1>{post.title}</h1>
          <div className="about">{`by ${post.username} on ${post.created}`}</div>
        </div>
        {user && Number(user.id) === Number(post.author_id) ? (
          <NavLink className="action" to={`/post/${post.id}`}>
            Edit
          </NavLink>
        ) : null}
      </header>
      <p className="body">{post.body}</p>
    </article>
  ));

  return (
    <>
      <header>
        <h1>Posts</h1>
        {user ? (
          <NavLink className="action" to="/create">
            New
          </NavLink>
        ) : null}
      </header>
      {renderPosts}
    </>
  );
};

export default Posts;
