// frontend/src/react/blog/Create.jsx
// @flow
import * as React from "react";
import PostForm from "../common/PostForm";
import Title from "../common/Title";

function Create() {
  return (
    <>
      <Title title="New post" />
      <header>
        <h1>New post</h1>
      </header>
      <PostForm url="/blog/post/create" />
    </>
  );
}

export default Create;

// frontend/src/vue/blog/Create.vue
<template>
  <post-form :form="form" title="Create" url="/blog/post/create" />
</template>

<script>
import { mapState } from "vuex";
import PostForm from "./PostForm.vue";

export default {
  components: {
    PostForm
  },
  data: () => ({
    error: "",
    form: {
      title: "",
      body: ""
    }
  }),
  computed: mapState(["user"])
};
</script>
